name: Build packages for windows

inputs:
    package-file-name-prefix:
        required: true
        type: string
    package-artifact-name-prefix:
        required: true
        type: string
    backend-artifact-name-prefix:
        required: true
        type: string

runs:
    using: "composite"
    steps:
        - name: Download windows-x64 backend file
          uses: actions/download-artifact@v4
          with:
              name: ${{ inputs.backend-artifact-name-prefix }}-windows-x64
              path: ${{ runner.temp }}\backend

        - name: Download linux-amd64 packaged files
          uses: actions/download-artifact@v4
          with:
              name: ${{ inputs.package-artifact-name-prefix }}-linux-amd64
              path: ${{ runner.temp }}\package

        - name: Extract frontend files from linux-amd64 package
          shell: pwsh
          run: |
              New-Item -ItemType Directory -Path package
              tar -xzf (Get-ChildItem ${{ runner.temp }}\package\${{ inputs.package-file-name-prefix }}-linux-amd64.tar.gz) -C package

        - name: Package windows-x64 package
          shell: pwsh
          run: |
              New-Item -ItemType Directory -Path "splitchill-ai"
              New-Item -ItemType Directory -Path "splitchill-ai\data"
              New-Item -ItemType Directory -Path "splitchill-ai\storage"
              New-Item -ItemType Directory -Path "splitchill-ai\log"
              Copy-Item ${{ runner.temp }}\backend\splitchill-ai.exe -Destination splitchill-ai\
              Copy-Item -Recurse -Force package\public -Destination splitchill-ai\public
              Copy-Item -Recurse -Force conf -Destination splitchill-ai\conf
              Copy-Item -Recurse -Force templates -Destination splitchill-ai\templates
              Copy-Item .\LICENSE -Destination splitchill-ai\
              Push-Location splitchill-ai
              7z a -r -tzip -mx9 ..\${{ inputs.package-file-name-prefix }}-windows-x64.zip *
              Pop-Location
              Remove-Item -Recurse -Force splitchill-ai

        - name: Upload windows artifact
          uses: actions/upload-artifact@v4
          with:
              name: ${{ inputs.package-artifact-name-prefix }}-windows-x64
              path: ${{ inputs.package-file-name-prefix }}-windows-x64.zip
              if-no-files-found: error
